# docker-compose.yml
version: '3'

services:
  app:
    build: .
    image: api:local
    ports:
      # Service will be accessible on the host at port 8080.
      - '8080:${PORT:-8080}'
    environment:
      # /run/docs/reference/container-contract
      PORT: ${PORT:-8080}
      K_SERVICE: api
      K_REVISION: 0
      K_CONFIGURATION: api
