name: Code format, lint, testing

on:
  pull_request:
    branches:
      - dev
      - staging
      - main
  push:
    branches:
      - '*'

jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Code Formatter
        run: npm run format

      - name: Lint Test
        run: npm run lint
